### ISSUE TITLE
memory leak problem

### ISSUE THREAD

**Issue by pokerc** [noirello/pyorc#1]
When i try to read the two orc file, and i found the memory of the first reader have not been released. I found no __del__() in the Reader. How can i release the memory.
`
import os
import sys
import pyorc
from memory_profiler import profile
import gc

@profile
def main():
    fr = open("000748_0", "rb")
    r = pyorc.reader
    reader = r.Reader(fr)
    for i in range(100):
        pass
    a = reader.read(1000)
    b = reader.read(20000)
    c = reader.read(10000)
    del reader
    del r
    del a,b,c
    fr.close()
    gc.collect()
    fr = open("001751_0","rb")
    r = pyorc.reader
    reader = r.Reader(fr)
    cnt = reader.__len__()
    for i in range(cnt):
        a = reader.__next__()
    c = [1] * (10 ** 6)

if __name__ == '__main__':
    main()`

**Comment by noirello** [comment]
Hello, thank you for reporting it.

I've looked into it, and found an unnecessary `pybind11:object` release call that created dangling/never decremented bytes objects during reading the ORC file. Creating a Reader object includes reading the metadata from the file, thus the faulty function was invoked during the Reader's initialisation.

I pushed the fix [commit](https://github.com/noirello/pyorc/commit/c0556e07d8ca989ddda7cdc312053fbdbfde4549) to upstream.
