### ISSUE TITLE
Footer is corrupt: malformed link from type 0 to 0

### ISSUE THREAD

**Issue by fritzb** [noirello/pyorc#11]
I'm getting the following error when reading the ORC file:
  File "/Users/fritzbudiyanto/.local/share/virtualenvs/workflows-66nlkjZ7/lib/python3.7/site-packages/pyorc/reader.py", line 67, in __init__
    fileo, batch_size, column_indices, column_names, struct_repr, conv
pyorc.errors.ParseError: Footer is corrupt: malformed link from type 0 to 0

<another one>
pyorc.errors.ParseError: Footer is corrupt: types(272536112) not exists

The file can be read properly with Java ORC client. How to debug this further ?

**Comment by noirello** [comment]
At first glance, it looks like some kind of a bug in the C++ implementation. Can you share this ORC file?

**Comment by fritzb** [comment]
[https://www.dropbox.com/sh/qnakeftkq7yi8wp/AAC7T6h5UKjQL8pGPUh_6dOra?dl=0](url)

**Comment by noirello** [comment]
I couldn't reproduce the error with the following code:
```python3
import pyorc
import glob

for orc_file in glob.glob("./issue/*"):
    with open(orc_file, "rb") as orc_data:
        reader = pyorc.Reader(orc_data)
        print(orc_file, len(list(reader)))
```

Output:
```
python3 malformed-issue.py
./issue/part-0-0 10
./issue/part-0-1 5
./issue/part-0-2 6
./issue/part-0-3 3
./issue/part-0-4 1
./issue/roadmetrics_lane1.orc 0
./issue/roadmetrics_omap_length.orc 0
./issue/roadmetrics_posegraph.orc 0
```

**Comment by fritzb** [comment]
If I have this import statement, the corruption starts to happen:

`from google.protobuf import json_format
`

Protobuf pypi version is protobuf-3.12.2
Which protobuf were you using when building the 0.3 package ?

**Comment by noirello** [comment]
I built it with the 1.6.3 ORC Core which uses the protobuf 3.5.1 by default.

**Comment by fritzb** [comment]
I downgraded to protobuf 3.6.1 and it works now
