### ISSUE TITLE
Not able to install pyorc on linux machine present on GCP

### ISSUE THREAD

**Issue by prasadkedari** [noirello/pyorc#14]
Error:
linux-x86_64-3.7/src/_pyorc/_pyorc.o -DVERSION_INFO="0.3.0" -std=c++17 -fvisibility=hidden
    In file included from src/_pyorc/_pyorc.cpp:1:
    src/_pyorc/Reader.h:7:10: fatal error: orc/OrcFile.hh: No such file or directory
     #include "orc/OrcFile.hh"
              ^~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-l9pn60e0/pyorc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.c
lose();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-gxlj1vmw/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 
in /tmp/pip-install-l9pn60e0/pyorc/

**Comment by prasadkedari** [comment]
Using python version 3.7

**Comment by noirello** [comment]
Are yo trying to install it from wheel (via pip) or from source?
Which distro are you using?

**Comment by shannoncolavita** [comment]
also getting this error on pythin v 3.6. I downloaded tar & extracted, the file is def missing, there is no orc dir
![image](https://user-images.githubusercontent.com/3765810/85016885-e2ec2d00-b16a-11ea-903d-513a34b69299.png)

**Comment by noirello** [comment]
To install the module from source, first you need to get Apache ORC source and compile it. There's a extra command for the `setup.py` to do that.

```
python3 setup.py build_orc
python3 setup.py install
```
 
You also need `cmake` for building the ORC lib and the `pybind11` module for installing pyorc.

**Comment by shannoncolavita** [comment]
Thanks but really wanted an easy install, don't want to be building local
c++ libs, now looking at another orc reader for quick reuse

**Comment by noirello** [comment]
manylinux wheel packages are uploaded to pypi for Python 3.6, 3.7 and 3.8. Also for Mac OS (3.7, 3.8). I'm not sure why pip install doesn't use them. Which OS distribution are you using?

**Comment by shannoncolavita** [comment]
i'm using Ubuntu 18.04.4 LTS, able to install other pip packages

**Comment by noirello** [comment]
Thank you for that info, I was able to reproduce in a Docker container with an `ubuntu:18.04` image.

Turned out that the pip shipped with Ubuntu 18.04 (pip 9.0.1) is [too old](https://github.com/pypa/manylinux/issues/389) to handle `manylinux2010` wheels. By upgrading to 19.0 or newer, you should be able to install the module without needing to compile it locally.

**Comment by shannoncolavita** [comment]
thanks for looking into this, will try that at some stage!
