### ISSUE TITLE
Metadata support?

### ISSUE THREAD

**Issue by pshirshov** [noirello/pyorc#15]
Seems like it's not possible to read user metadata, would be nice to have such a feature. Thanks!

**Comment by noirello** [comment]
You can with the latest version (v0.3.0). The Reader has a [metadata](https://pyorc.readthedocs.io/en/latest/api.html#pyorc.Reader.metadata) property that returns a dict.

**Comment by pshirshov** [comment]
Oh, my bad. Thanks!

**Comment by calebwin** [comment]
@pshirshov @noirello 

This doesn't seem to be working...
```python
In [19]: f = open("python/cudf/cudf/tests/data/orc/TestOrcFile.testDate2038.orc", "rb")

In [20]: r = pyorc.Reader(f)

In [21]: r.metadata
Out[21]: {}
```

I'm using datasets from here - https://github.com/rapidsai/cudf/tree/branch-0.15/python/cudf/cudf/tests/data/orc.

I'm using version 0.3.0 and `r.read()` seems to work fine. Is this supposed to work?

**Comment by noirello** [comment]
Not every ORC file has user metadata, try `TestOrcFile.metaData.orc`.

It was probably an unwise naming, calling the attribute simply `metadata` (as it's referred in the C++ Core library). The `user_metadata` name would be less ambiguous.

**Comment by calebwin** [comment]
@noirello Thanks. Do you think I could parse this using protobuf? And would you know what from the ORC proto definition do I parse the `big` field into?

**Comment by calebwin** [comment]
Hmm... I want to get column statistics. But it seems like `big` only contains user metadata key-value pairs [1].

[1] https://github.com/noirello/pyorc/blob/92de79139bbea6d917e58453af546e3ee0a3e607/src/_pyorc/Reader.cpp#L432-L440

**Comment by calebwin** [comment]
Alright, I'm now seeing that this is part of the API, which is great!
```python
r = pyorc.Reader(open("TestOrcFile.testStripeLevelStats.orc", "rb"))
r.read_stripe(2)[2].statistics
```
To confirm, if I do the above, I'm not reading in the stripe itself, only metadata stored in the file footer - right?

**Comment by noirello** [comment]
Indeed, you're reading the statistics of the third column in the third stripe from the footer.

**Comment by calebwin** [comment]
That's perfect! Thanks.

**Comment by calebwin** [comment]
Alright, that makes sense. It just seems strange that `getStripeStats` [1] reads the row index of the stripe and the API doesn't have a way to get stripe-level stats without also getting row-level stats.

[1] https://github.com/apache/orc/blob/c26ff4c351d7c34c4272442a6874703f510282a8/c%2B%2B/src/Reader.cc#L627-L655

**Comment by fehtemam** [comment]
Can we read stripes by columns? Like when doing r.read_stripe(2)[2] is there a way to read the resulting column object or is statistics the only method we can apply to a stripe object?

**Comment by noirello** [comment]
Currently, only the statistics can be accessed from Column objects.

**Comment by fehtemam** [comment]
@noirello Thanks a lot for the response and for the great library. That was my guess looking at the methods of Column object. Do you have any suggestion on how one, in general, might read stripes by columns instead of rows? I am dealing with very different data types per column so reading in rows makes it difficult to convert to numpy array (or any other data structure) since one row includes several incompatible types. Instead of reading stripes, I thought of reading the orc file by column (into Reader objects) but number of columns are not known until a Reader object is already created so that we can get the schema and extract number of columns and their names. So that alternative idea made for a catch-22.

**Comment by noirello** [comment]
The best that you can do is select the necessary columns to read with Reader's `column_names` or `column_indices` parameters, but still going to read the data row by row. It will just ignore/skip the non-selected columns in the ORC file. The C++ library only provides a RowReader API. This is why I abandoned the idea of exposing the data in the Column object, so far. It was to much work and complexity for a small benefit.

Also, in the future, it's better to open a new issue, when your topic's just loosely related.
