### ISSUE TITLE
Conda?

### ISSUE THREAD

**Issue by calebwin** [noirello/pyorc#16]
This would be potentially usable by [cuDF](https://github.com/rapidsai/cudf/) if it were uploaded to Anaconda/conda-forge. Could this be done soon?

**Comment by noirello** [comment]
I'm not that familiar with the Anaconda ecosystem.
I registered and uploaded the latest version manually: https://anaconda.org/noirello/pyorc

But I'm not sure that this was on your mind.

**Comment by calebwin** [comment]
Well, what we really need is for it to be uploaded to `anaconda/conda-forge` [1]. This would make pyorc easily usable in Conda projects.

[1] https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by noirello** [comment]
I see, I'm not against the idea but I don't think I'll have the time to do it in the next couple of days.

**Comment by jornfranke** [comment]
Please let me know if I can assist here. You basically need to fork:
https://github.com/conda-forge/staged-recipes

Then create in the folder recipes a subfolder "pyorc" add a LICENSE file and a meta.yaml file. I cant try to prepare a meta.yaml file for you in this issue if you are interested.
Afterwards you simply create a pull request and the they integrate the package.

**Comment by noirello** [comment]
[Opened it for 0.4.0](https://github.com/conda-forge/staged-recipes/pull/13658), I have some doubt about the compiling, but will see how far it goes.

**Comment by noirello** [comment]
I think it's done: https://anaconda.org/conda-forge/pyorc

**Comment by jornfranke** [comment]
great thank you a lot!
