### ISSUE TITLE
Missing ORC 1.6.3 version on apache download

### ISSUE THREAD

**Issue by shahjapan** [noirello/pyorc#18]
Apache has released newer version of ORC file i.e. 1.6.4 and they have moved their older version source to archive repository - which is causing HTTP 404 failure while building orc binaries.
i.e. python setup.py build_orc failing

Old URL: https://downloads.apache.org/orc/orc-1.6.3/orc-1.6.3.tar.gz
Moved to: https://archive.apache.org/dist/orc/orc-1.6.3/orc-1.6.3.tar.gz

> 
> $ python setup.py build_orc
> running build_orc
> Build ORC C++ Core library
> error: HTTP Error 404: Not Found

**Comment by noirello** [comment]
You can pass the new version for the build script with a parameter:
``` python setup.py build_orc --orc-version=1.6.4```
Or build the old one by changing the source-url:
``` python setup.py build_orc --source-url=https://archive.apache.org/dist/orc/```

**Comment by shahjapan** [comment]
Thanks @noirello it worked.
