### ISSUE TITLE
Problem of building from the source: C++ 11 vs 14

### ISSUE THREAD

**Issue by ericsun2** [noirello/pyorc#21]
When we try to build from the 0.3.0 source, there are issues with handling compiler options (C++ 11 compiler is installed on our Linux hosts), but the package has a bug in testing the feature. Then, the package has an issue with 2 build tasks, where one needs another, but they are not scheduled in order. 
Finally, there is one line in the code that uses `C++ 14 feature`, despite the package claiming that it supports C++ 11. By using some #ifdef checks in the C++ code we are able to put an equivalent C++ 11 implementation in the code and after that the package builds on both Linux and macOS (where compiler actually uses C++ 17 features).

**Comment by noirello** [comment]
I [removed](https://github.com/noirello/pyorc/commit/8a74dca8cbe32e1ac49112fae4aee05403e161f0) the function that used C++14 feature.
Also added more descriptions about how to install the package from source to the docs.

Could you elaborate on the mentioned bug in testing the compiler feature?

**Comment by ericsun2** [comment]
I have to build the source code (instead of directly reuse the existing wheel file) on my CI hosts, where I don't have C++ 14 installed. I encounter compile error during CI.

Can I try the new version (with C++ 14 feature removed) now?

**Comment by noirello** [comment]
The commit that removes the C++14 feature is on the master branch. You can try it from there, but I haven't made a new release (since 0.3.0) yet.
