### ISSUE TITLE
fatal error C1083: Cannot open include file: 'orc/OrcFile.hh': No such file or directory

### ISSUE THREAD

**Issue by blueRegen** [noirello/pyorc#28]
Hello,

Any one having a solution for this - fatal error C1083: Cannot open include file: 'orc/OrcFile.hh': No such file or directory
seems like a widespread issue that many are facing.

Help is appreciated. 
thanks. 

building 'pyorc._pyorc' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    creating build\temp.win-amd64-3.8\Release\src\_pyorc
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\a\python\lib\site-packages\pybind11\include -Ic:\a\python\lib\site-packages\pybind11\include -Ideps/include/ -Ic:\a\python\include -Ic:\a\python\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpsrc/_pyorc\_pyorc.cpp /Fobuild\temp.win-amd64-3.8\Release\src/_pyorc\_pyorc.obj /EHsc /DVERSION_INFO=\"0.3.0\"
    _pyorc.cpp
    c:\users\narasas\appdata\local\temp\pip-install-aokjbm44\pyorc_2ceb6efca0c442ed869ea875a6fb7421\src\_pyorc\Reader.h(7): fatal error C1083: Cannot open include file: 'orc/OrcFile.hh': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\a\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\narasas\\AppData\\Local\\Temp\\pip-install-aokjbm44\\pyorc_2ceb6efca0c442ed869ea875a6fb7421\\setup.py'"'"'; __file__='"'"'C:\\Users\\narasas\\AppData\\Local\\Temp\\pip-install-aokjbm44\\pyorc_2ceb6efca0c442ed869ea875a6fb7421\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\narasas\AppData\Local\Temp\pip-record-ns_oflt3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\a\python\Include\pyorc' Check the logs for full command output.

**Comment by blueRegen** [comment]
anyone to help me on this?  Unable to move past this...

**Comment by noirello** [comment]
As mentioned in Issue #9, Windows is not a supported platform for PyORC.

I'm working on it to change that right now.

**Comment by noirello** [comment]
Version 0.4.0 now has experimental Windows support. Win64 wheels are uploaded to PyPI.

**Comment by blueRegen** [comment]
Noirello,

Works incredibly flawlessly.

import pyorc

with open("./1.orc", "rb") as data:
    reader = pyorc.Reader(data)
    i = 0
    for row in reader:
        i += 1
        if i < 10 :
            print(row)

![image](https://user-images.githubusercontent.com/22227161/104248634-e06b6080-5437-11eb-9ca3-25626f202ff3.png)
![image](https://user-images.githubusercontent.com/22227161/104248678-f1b46d00-5437-11eb-9450-63589ad03435.png)

we are going to put this to performance test - 
we are going to process about 5000 files  large files. 

thank you so much for your help.   I will stay in touch. 

best regards
