### ISSUE TITLE
PyPI release to support Python 3.9

### ISSUE THREAD

**Issue by rzeyde-varada** [noirello/pyorc#29]
First of all - many thanks for this great project, much appreciated!

We would appreciate if you could please create a new PyPI release to support Python 3.9 🙏 
IIUC, the latest release support Python 3.6 to 3.8: https://pypi.org/simple/pyorc/

**Comment by noirello** [comment]
Released 0.4.0 with 3.9 wheels.

**Comment by rzeyde-varada** [comment]
Many thanks!
