### ISSUE TITLE
unable to insert Long value.

### ISSUE THREAD

**Issue by maranmani978** [noirello/pyorc#3]
Unable to insert int values greater than sys.maxSize

**Comment by noirello** [comment]
You won't be able to write that in a `bigint` typed field.

The `sys.maxsize` is equal to `2**63 - 1` on a 64bit system, which is the maximal value that can be store in a C/C++ `int64_t` variable. ORC's LongBatchVector is used for storing `boolean`/`byte`/`short`/`int`/`bigint` types in an ORC file is based on `int64_t` arrays.

If you need to work that large numbers, then use the decimal type:
```python
import pyorc
import sys
from decimal import Decimal

w = pyorc.Writer(data, "decimal(20,0)")
w.write(Decimal(sys.maxsize + 1))
w.close()

r = pyorc.Reader(data)
next(r) # Decimal('9223372036854775808')
```
