### ISSUE TITLE
save orc contents to csv

### ISSUE THREAD

**Issue by blueRegen** [noirello/pyorc#30]
Hi

Is there a way to save ORC file contents to CSV?
I want to save a_reader to a CSV file. 

```python3
import pyorc

with open("./2.orc", "rb") as data:
    a_reader = pyorc.Reader(data)
    print(type(reader))
    i = 0
    for row in a_reader:
        i += 1
        if i < 10:
            payload = row[1]
            print(type(payload))
            #print(row[1])
            print("")
```
thanks.

**Comment by fehtemam** [comment]
You need to read your Reader object first. Either read it in whole or read stripes. I would do something like this:
```python
import pandas as pd
import pyorc
reader = pyorc.Reader(data)
df = pd.DataFrame(reader)
df.to_csv('path_to_file.csv', index=False)
```
Pandas makes it really easy to save your data to many formats including CSV.

**Comment by blueRegen** [comment]
@fehtemam   works like a charm.

thank you so much for the help.
