### ISSUE TITLE
Got installation error - Trying to install on Alpine 

### ISSUE THREAD

**Issue by blueRegen** [noirello/pyorc#31]
Hi 

Anyone successfully installed on alpine docker?
I am getting an error.

/ # python3 --version
Python 3.8.7

/# gcc --version
gcc (Alpine 10.2.1_pre1) 10.2.1 20201203
Copyright (C) 2020 Free Software Foundation, Inc.

/ # pip install pyorc==0.3.0
Collecting pyorc==0.3.0
  Using cached pyorc-0.3.0.tar.gz (41 kB)
Requirement already satisfied: pybind11>=2.5 in /usr/lib/python3.8/site-packages (from pyorc==0.3.0) (2.6.1)
Using legacy 'setup.py install' for pyorc, since package 'wheel' is not installed.
Installing collected packages: pyorc
    Running setup.py install for pyorc ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5dn_w2gy/pyorc_f3b26ecd51574b30bc2257a2e63b7d5e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5dn_w2gy/pyorc_f3b26ecd51574b30bc2257a2e63b7d5e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wrlz7rvf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/pyorc
         cwd: /tmp/pip-install-5dn_w2gy/pyorc_f3b26ecd51574b30bc2257a2e63b7d5e/
    Complete output (42 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/pyorc
    copying src/pyorc/writer.py -> build/lib.linux-x86_64-3.8/pyorc
    copying src/pyorc/converters.py -> build/lib.linux-x86_64-3.8/pyorc
    copying src/pyorc/reader.py -> build/lib.linux-x86_64-3.8/pyorc
    copying src/pyorc/errors.py -> build/lib.linux-x86_64-3.8/pyorc
    copying src/pyorc/enums.py -> build/lib.linux-x86_64-3.8/pyorc
    copying src/pyorc/typedescription.py -> build/lib.linux-x86_64-3.8/pyorc
    copying src/pyorc/__init__.py -> build/lib.linux-x86_64-3.8/pyorc
    running egg_info
    writing pyorc.egg-info/PKG-INFO
    writing dependency_links to pyorc.egg-info/dependency_links.txt
    writing requirements to pyorc.egg-info/requires.txt
    writing top-level names to pyorc.egg-info/top_level.txt
    reading manifest file 'pyorc.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    writing manifest file 'pyorc.egg-info/SOURCES.txt'
    running build_ext
    creating tmp
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.8 -c /tmp/tmp9meo18pg.cpp -o tmp/tmp9meo18pg.o -std=c++17
    building 'pyorc._pyorc' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    creating build/temp.linux-x86_64-3.8/src/_pyorc
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/lib/python3.8/site-packages/pybind11/include -I/usr/lib/python3.8/site-packages/pybind11/include -Ideps/include/ -I/usr/include/python3.8 -c src/_pyorc/_pyorc.cpp -o build/temp.linux-x86_64-3.8/src/_pyorc/_pyorc.o -DVERSION_INFO="0.3.0" -std=c++17 -fvisibility=hidden
    In file included from /usr/lib/python3.8/site-packages/pybind11/include/pybind11/pytypes.h:12,
                     from /usr/lib/python3.8/site-packages/pybind11/include/pybind11/cast.h:13,
                     from /usr/lib/python3.8/site-packages/pybind11/include/pybind11/attr.h:13,
                     from /usr/lib/python3.8/site-packages/pybind11/include/pybind11/pybind11.h:45,
                     from src/_pyorc/Reader.h:4,
                     from src/_pyorc/_pyorc.cpp:1:
    /usr/lib/python3.8/site-packages/pybind11/include/pybind11/detail/common.h:122:10: fatal error: Python.h: No such file or directory
      122 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5dn_w2gy/pyorc_f3b26ecd51574b30bc2257a2e63b7d5e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5dn_w2gy/pyorc_f3b26ecd51574b30bc2257a2e63b7d5e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wrlz7rvf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/pyorc Check the logs for full command output.

**Comment by blueRegen** [comment]
I am currently trying this 

https://stackoverflow.com/questions/62597014/failed-to-install-pyorc-on-alpine-docker-container/62598006#62598006

**Comment by blueRegen** [comment]
PS C:\a\python\w\docker> docker build -t alp1 .
[+] Building 50.1s (11/16)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                      0.0s
 => => transferring dockerfile: 893B                                                                                                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/python:3.8.3-alpine                                                                                                                                                                                                    9.4s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                                                                                                                             0.0s
 => [builder 1/8] FROM docker.io/library/python:3.8.3-alpine@sha256:c5623df482648cacece4f9652a0ae04b51576c93773ccd43ad459e2a195906dd                                                                                                                                      8.8s
 => => resolve docker.io/library/python:3.8.3-alpine@sha256:c5623df482648cacece4f9652a0ae04b51576c93773ccd43ad459e2a195906dd                                                                                                                                              0.0s
 => => sha256:8ecf5a48c789c6762846613726831aa4e818570a0f2c5eea0250838da846261c 7.14kB / 7.14kB                                                                                                                                                                            0.0s
 => => sha256:df20fa9351a15782c64e6dddb2d4a6f50bf6d3688060a34c4014b0d9a752eb4c 2.80MB / 2.80MB                                                                                                                                                                            1.5s
 => => sha256:36b3adc4ff6ffb76ae233f0a92177205845aaf3e9a39e0f96405dabd1423edc9 280.84kB / 280.84kB                                                                                                                                                                        0.7s
 => => sha256:7031d6d6c7f13f9b47350f2e479949982cb576e2a0053d7578fcfe386e8b1f17 22.30MB / 22.30MB                                                                                                                                                                          7.5s
 => => sha256:c5623df482648cacece4f9652a0ae04b51576c93773ccd43ad459e2a195906dd 1.65kB / 1.65kB                                                                                                                                                                            0.0s
 => => sha256:6c1b18373c4f94353308097772e97ff4d0e596ac3d06cc4b00c3bdc52cd5e8b6 1.37kB / 1.37kB                                                                                                                                                                            0.0s
 => => sha256:81b7f5a7444b8cb64dff0006b57bc7c5eb6249e6a7698017bb5a790caf069ce7 229B / 229B                                                                                                                                                                                0.9s
 => => sha256:0f8a54c5d7c710ded3c3fa9ff71e9885003d375d62545f5e767352fc818b3bd6 1.93MB / 1.93MB                                                                                                                                                                            2.0s
 => => extracting sha256:df20fa9351a15782c64e6dddb2d4a6f50bf6d3688060a34c4014b0d9a752eb4c                                                                                                                                                                                 0.2s
 => => extracting sha256:36b3adc4ff6ffb76ae233f0a92177205845aaf3e9a39e0f96405dabd1423edc9                                                                                                                                                                                 0.1s
 => => extracting sha256:7031d6d6c7f13f9b47350f2e479949982cb576e2a0053d7578fcfe386e8b1f17                                                                                                                                                                                 0.6s
 => => extracting sha256:81b7f5a7444b8cb64dff0006b57bc7c5eb6249e6a7698017bb5a790caf069ce7                                                                                                                                                                                 0.0s
 => => extracting sha256:0f8a54c5d7c710ded3c3fa9ff71e9885003d375d62545f5e767352fc818b3bd6                                                                                                                                                                                 0.1s
 => [builder 2/8] RUN apk add gcc g++ musl-dev cmake make                                                                                                                                                                                                                26.0s
 => [builder 3/8] RUN mkdir build                                                                                                                                                                                                                                         0.5s
 => [builder 4/8] WORKDIR /build                                                                                                                                                                                                                                          0.1s
 => [builder 5/8] RUN pip install pybind11 wheel                                                                                                                                                                                                                          2.5s
 => [builder 6/8] RUN pip download --no-binary :all: --no-deps pyorc==0.3.0 && tar -xvf *.tar.gz                                                                                                                                                                          1.4s
 => ERROR [builder 7/8] RUN cd pyorc-0.3.0 && python3 setup.py build_orc                                                                                                                                                                                                  1.1s
------
 > [builder 7/8] RUN cd pyorc-0.3.0 && python3 setup.py build_orc:
#11 0.438 running build_orc
#11 0.438 Build ORC C++ Core library
#11 1.057 error: HTTP Error 404: Not Found
------
executor failed running [/bin/sh -c cd pyorc-${VERSION} && python3 setup.py build_orc]: exit code: 1
PS C:\a\python\w\docker>
---------------------------------

Docker file

FROM python:3.8.3-alpine AS builder
RUN apk add gcc g++ musl-dev cmake make
ARG VERSION=0.3.0

RUN mkdir build
WORKDIR /build
RUN pip install pybind11 wheel
RUN pip download --no-binary :all: --no-deps pyorc==${VERSION} && tar -xvf *.tar.gz
RUN cd pyorc-${VERSION} && python3 setup.py build_orc
RUN cd pyorc-${VERSION} && python3 setup.py bdist_wheel

FROM python:3.8.3-alpine
ARG VERSION=0.3.0

COPY --from=builder /build/pyorc-${VERSION}/dist/pyorc-${VERSION}-*.whl /tmp/
# Adding libstdc++, because the wheel expects that the libstdc++.so is presented on the system.
# Adding tzdata, because the ORC C++ lib needs to have a localtime set.
RUN apk add libstdc++ tzdata
# Setting localtime to UTC.
RUN ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
RUN pip install /tmp/pyorc-${VERSION}-*.whl && rm -rf /tmp/pyorc-${VERSION}-*.whl

**Comment by blueRegen** [comment]
spent few hours to get this to work on alpine.
see attached image. 

thanks for the help. 
![Alpine Install Error](https://user-images.githubusercontent.com/22227161/104880506-ab767680-592d-11eb-9843-4940db57686a.JPG)

**Comment by noirello** [comment]
Hi, try [this SO answer](https://stackoverflow.com/a/62605348/1024034) instead.

Use version 0.4.0, the HTTP Error during the build_orc command was raised, because the 1.6.3 ORC Core lib version is moved to a different path. You can change the orc lib version or the source url with these params: `--orc-version`, `--source-url`

**Comment by blueRegen** [comment]
The above SO with version .4 works flawlessly.  

thanks for the help noirello.
