### ISSUE TITLE
set_metadata() casts to str()

### ISSUE THREAD

**Issue by micahcc** [noirello/pyorc#45]
This line incorrectly cast from py::bytes to py::string. If the data is in fact binary then this will fail, instead I believe this should be directly cast to a std::string

 https://github.com/noirello/pyorc/blob/99f642a63bf2fa6a3e84b11d3aca55dafd773068/src/_pyorc/Writer.cpp#L162

**Comment by noirello** [comment]
Thank you, I've just fixed it and pushed to master.

**Comment by noirello** [comment]
Released in 0.6.0.
