### ISSUE TITLE
Issue with dates

### ISSUE THREAD

**Issue by ghunt-cp** [noirello/pyorc#5]
I like pyorc's interface. It's been easy to use. However, I'm running into a slight problem. If I try to write a date, then when I read the date, it is one day off. If I run the test_write_primitive_type test, then it fails on dates as well:

    @pytest.mark.parametrize("orc_type,values", TESTDATA)
    def test_write_primitive_type(orc_type, values):
        data = io.BytesIO()
        writer = Writer(data, orc_type)
        for rec in values:
            writer.write(rec)
        writer.close()
    
        data.seek(0)
        reader = Reader(data)
        if orc_type == "float":
            result = reader.read()
            assert len(result) == len(values)
            for res, exp in zip(result, values):
                if exp is None:
                    assert res is None
                else:
                    assert math.isclose(res, exp, rel_tol=1e-07, abs_tol=0.0)
        else:
>           assert reader.read() == values
E           assert [datetime.dat...2019, 11, 10)] == [datetime.dat...2019, 11, 11)]
E             At index 0 diff: datetime.date(1909, 12, 7) != datetime.date(1909, 12, 8)
E             Use -v to get the full diff

I encountered this problem in python 3.6 on a CentOS server, however, I replicated on a Mac using python 3.7.

**Comment by noirello** [comment]
Never checked on CentOS, but I failed to reproduce manually on a Mac with Python 3.7.6 (Clang 11.0.0) using the 0.2.0 release.
The CI runs the tests on Ubuntu and Mac (with 3.6, 37, 3.8).  

```
platform darwin-- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/local/opt/bin/python3.7
cachedir: .pytest_cache
rootdir: /Users/noirello/pyorc
collected 11 items

tests/test_writer.py::test_write_primitive_type[string-values0] PASSED
tests/test_writer.py::test_write_primitive_type[binary-values1] PASSED
tests/test_writer.py::test_write_primitive_type[int-values2] PASSED
tests/test_writer.py::test_write_primitive_type[bigint-values3] PASSED
tests/test_writer.py::test_write_primitive_type[float-values4] PASSED
tests/test_writer.py::test_write_primitive_type[double-values5] PASSED
tests/test_writer.py::test_write_primitive_type[boolean-values6] PASSED
tests/test_writer.py::test_write_primitive_type[timestamp-values7] PASSED
tests/test_writer.py::test_write_primitive_type[date-values8] PASSED
tests/test_writer.py::test_write_primitive_type[decimal(10,7)-values9] PASSED
tests/test_writer.py::test_write_primitive_type[decimal(38,6)-values10] PASSED
```

You can create an own Date converters and change the [default one](https://github.com/noirello/pyorc/blob/v0.2.0/src/pyorc/converters.py#L34). A converter that prints the input params before converting them to the Writer/Reader can give us more insights what goes wrong.

**Comment by ghunt-cp** [comment]
I added print statements to the date converter. I believe that the issue is a timezone issue. The input was correct, however, the return is causing an issue. Here's a simple python script that illustrates the issue:

from datetime import datetime, date, timezone

print(datetime.fromtimestamp(0))
print(datetime.fromtimestamp(0, timezone.utc))
print(date.fromtimestamp(0))

with the output from my machine:
1969-12-31 19:00:00
1970-01-01 00:00:00+00:00
1969-12-31

In converters.py, in the timestamp converter, the from_orc function is passing timezone.utc to the fromtimestamp function. Ideally, we would do the same in the date converter, however, date's fromtimestamp function does not support passing in a timezone. I changed the from_orc function in the date converter to:
return datetime.fromtimestamp(days * 24 * 60 * 60, timezone.utc).date()
and then the tests started passing for me.

**Comment by ghunt-cp** [comment]
Note that if the machine that you run the tests on is on utc, then you wouldn't see this problem because the local time and utc would be the same thing.

**Comment by noirello** [comment]
Thank you for looking into it.

All of my test runs were in timezones with non-negative UTC offsets. I should fix that.

For solution, I'm planning to leave out the `fromtimestamp` method entirely, and add timedelta days to the epoch date. Thus the `from_orc` will be similar to it's `to_orc` counterpart.

**Comment by ghunt-cp** [comment]
Awesome! Thanks!

**Comment by ghunt-cp** [comment]
Can you create a new release with this fix?

**Comment by noirello** [comment]
Done. Sorry for taking so long.
