### ISSUE TITLE
can't find '__main__' module 

### ISSUE THREAD

**Issue by robinrosenberg** [noirello/pyorc#50]
Hi,

We're trying to create quite huge files using pyorc and it's way too slow, so I tried using pypy3, however I get this strange error when installing the pyorc depdendency. Only pyorc has this problem; everything else loads fine.

```
# pypy3 -m pip install pyorc
pypy3 wouldn't find modules
pypy3 -m pip install pyorc
Collecting pyorc
Using cached pyorc-0.6.0.tar.gz (54 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
ERROR: Command errored out with exit status 1:
command: /usr/bin/pypy3 /usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpd7wwooav
cwd: /tmp/pip-install-mki2amwp/pyorc
Complete output (1 lines):
/usr/bin/pypy3: can't find '__main__' module in '/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py'
----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/pypy3 /usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpd7wwooav Check the logs for full command output.
```

**Comment by noirello** [comment]
Hi, which platform are you trying to install?
After a quick search, it might be related to a [pip bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955414) on Debian. Have you tried [--force-reinstall](https://github.com/pypa/pip/issues/7946#issuecomment-606590604) pip?

**Comment by robinrosenberg** [comment]
Thank you! that seems to help

**Comment by noirello** [comment]
Glad to here it!

I'd be interested to hear about your experience running pyorc on PyPy. This is the first release to provide some PyPy support.
And not to crush your hopes, but I had to skip one of my larger integration test on the CI, because it ran so long with PyPy. :/ 
So it's possible you won't get that speed bump that you're looking for.
