### ISSUE TITLE
Issue with date time conversion?

### ISSUE THREAD

**Issue by jkamina** [noirello/pyorc#6]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-88a94d1d1745> in <module>
     22     with pyorc.Writer(data, "struct<TERM_ID:double,LAST_UPDATE_DATE:timestamp,LAST_UPDATED_BY:double,CREATION_DATE:timestamp,CREATED_BY:double,LAST_UPDATE_LOGIN:double,NAME:string,ENABLED_FLAG:string,DUE_CUTOFF_DAY:double,DESCRIPTION:string,TYPE:string,START_DATE_ACTIVE:timestamp,END_DATE_ACTIVE:timestamp,RANK:double,ATTRIBUTE_CATEGORY:string,ATTRIBUTE1:string,ATTRIBUTE2:string,ATTRIBUTE3:string,ATTRIBUTE4:string,ATTRIBUTE5:string,ATTRIBUTE6:string,ATTRIBUTE7:string,ATTRIBUTE8:string,ATTRIBUTE9:string,ATTRIBUTE10:string,ATTRIBUTE11:string,ATTRIBUTE12:string,ATTRIBUTE13:string,ATTRIBUTE14:string,ATTRIBUTE15:string,LANGUAGE:string,SOURCE_LANG:string>") as writer:
     23         for row in df.itertuples():
---> 24             writer.write(row)
     25     writer.close()

/usr/local/anaconda/lib/python3.7/site-packages/pyorc/converters.py in to_orc(obj)
     29     @staticmethod
     30     def to_orc(obj: datetime) -> Tuple[int, int]:
---> 31         return int(obj.replace(microsecond=0).timestamp()), obj.microsecond * 1000
     32 
     33 

TypeError: replace() takes no keyword arguments

**Comment by noirello** [comment]
I think one of the items in your tuple that you stated as a `timestamp` field in the ORC is actually not a `datetime` object (most likely a string).

**Comment by jkamina** [comment]
Hi, the field is definitely a timestamp. 

Here is a sample tuple:

Pandas(Index=0, TERM_ID='10060', LAST_UPDATE_DATE='2019-04-01 05:19:34.0', LAST_UPDATED_BY='66365', CREATION_DATE='2012-07-12 13:22:51.0', CREATED_BY='1128', LAST_UPDATE_LOGIN='94127479', NAME='BR_PCC', ENABLED_FLAG='Y', DUE_CUTOFF_DAY='', DESCRIPTION='', TYPE='STD', START_DATE_ACTIVE='2012-07-12 00:00:00.0', END_DATE_ACTIVE='', RANK='', ATTRIBUTE_CATEGORY='', ATTRIBUTE1='', ATTRIBUTE2='', ATTRIBUTE3='', ATTRIBUTE4='', ATTRIBUTE5='', ATTRIBUTE6='', ATTRIBUTE7='', ATTRIBUTE8='', ATTRIBUTE9='', ATTRIBUTE10='', ATTRIBUTE11='', ATTRIBUTE12='', ATTRIBUTE13='', ATTRIBUTE14='', ATTRIBUTE15='', LANGUAGE='KO', SOURCE_LANG='US')


I tried changing the schema definition to date instead  and it gave this error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-08223d99464b> in <module>
     23         for row in df.itertuples():
     24             print(row)
---> 25             writer.write(row)
     26     writer.close()

/usr/local/anaconda/lib/python3.7/site-packages/pyorc/converters.py in to_orc(obj)
     39     @staticmethod
     40     def to_orc(obj: date) -> int:
---> 41         return (obj - date(1970, 1, 1)).days
     42 
     43 

TypeError: unsupported operand type(s) for -: 'str' and 'datetime.date'

Any ideas?

**Comment by jkamina** [comment]
I guess, I should summarize what I am trying to do is, write a pd.DataFrame into ORC. Let me know if you have any suggestions

**Comment by noirello** [comment]
The default timestamp converter expects a standard `datetime` objects and converts it to a tuple of (seconds, nanoseconds). If you'd like to use a different type as ORC timestamp you need to write a custom converter based on the [original one](https://github.com/noirello/pyorc/blob/v0.2.0/src/pyorc/converters.py#L23).

```python
import pyorc

from pyorc.converters import ORCConverter
from pyorc.enums import TypeKind

class OwnTimestampConvert(ORCConverter):
  ...


 with pyorc.Writer(data, schema, converts,
     converters={TypeKind.TIMESTAMP: OwnTimestampConvert}
 ) as writer:
   ...

```

The custom convert could also help you in debugging. I'm not familiar with pandas' `Timestamp` object, but based on the documentation it should be a drop-in replacement for `datetime`.

**Comment by deanrabinowitz4** [comment]
I could be way off here, but it looks like the package from pypi (0.2.0) is not up to date with the repo.
