### ISSUE TITLE
Needs C++ compiler to pip install on Windows

### ISSUE THREAD

**Issue by nlogie1** [noirello/pyorc#9]
With Windows 10 and Python 3.8, `pip install pyorc` results in 
```
Collecting pyorc
  Using cached pyorc-0.2.0.tar.gz (39 kB)
Collecting pybind11>=2.4
  Using cached pybind11-2.5.0-py2.py3-none-any.whl (296 kB)
Installing collected packages: pybind11, pyorc
    Running setup.py install for pyorc ... error
    ERROR: Command errored out with exit status 1:
     command: '...\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'...\\pyorc\\setup.py'"'"'; __file__='"'"'...\\pip-install-av36s2u9\\pyorc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record '...\pip-record-87c7z330\install-record.txt' --single-version-externally-managed --compile --install-headers 
...
    building 'pyorc._pyorc' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 
...
```
As I cannot install MS Visual C, this keeps me from using `pyorc`.

**Comment by noirello** [comment]
Currently, Windows is not a supported platform.

I've tried to compile the ORC C++ core library on Windows, but it failed. It looks like that it should be able to be compiled on Windows, but it doesn't seem to be a top priority for the Apache ORC project.

**Comment by altmind** [comment]
tried to compile on windows w/ 2019 build tools( as https://wiki.python.org/moin/WindowsCompilers recommends its as a drop-in replacement for 2015/v14), and still getting `error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

I'm unable to locate the log for setuptools/wheel to find what command was not found.

**Comment by noirello** [comment]
Version 0.4.0 has uploaded Windows wheels in PyPI.
